#spring.application.name=Journal App
#server.port=8081
#
#spring.data.mongodb.uri=mongodb+srv://adityamalhotra911_db_user:uS3CjycDP7wFauwi@cluster0.wt1vqbf.mongodb.net/journaldb?retryWrites=true&w=majority
#spring.data.mongodb.auto-index-creation=true
#spring-data-mongodb-database=journaldb
#
#server.servlet.context-path=/journal